version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm install

  build:
    commands:
      - echo Build started on `date`
      - npm run build

artifacts:
  type: S3
  location: react-app-deploy-bucket2  # Specify your S3 bucket name
  name: ""  # Leave empty if you don't want to override the artifact name; it will use the default
  files:
    - '**/*'
  base-directory: build  # Directory where build files are located (usually "build" for React apps)
